server:
  port: 8090

spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/appdb
    username: appuser
    password: secret123
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: UTC
        hibernate.default_schema: public
